// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwVKS8xXeutUjXDsSIVbuLhTTn7AcNKHI',
    appId: '1:664222473723:web:8b0b220c9b7fd5d080bf5e',
    messagingSenderId: '664222473723',
    projectId: 'chat-app-b594b',
    authDomain: 'chat-app-b594b.firebaseapp.com',
    storageBucket: 'chat-app-b594b.firebasestorage.app',
    measurementId: 'G-CF61JGH5SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBGfzVIev1DOGZ61dDUKxo-GH6mT21WPc',
    appId: '1:664222473723:android:d7b8b63b2798b59680bf5e',
    messagingSenderId: '664222473723',
    projectId: 'chat-app-b594b',
    storageBucket: 'chat-app-b594b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBGX4soCHE9zNXN1s7S_SOD4Rs6671Ztg',
    appId: '1:664222473723:ios:35ebfd304640862c80bf5e',
    messagingSenderId: '664222473723',
    projectId: 'chat-app-b594b',
    storageBucket: 'chat-app-b594b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBGX4soCHE9zNXN1s7S_SOD4Rs6671Ztg',
    appId: '1:664222473723:ios:35ebfd304640862c80bf5e',
    messagingSenderId: '664222473723',
    projectId: 'chat-app-b594b',
    storageBucket: 'chat-app-b594b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwVKS8xXeutUjXDsSIVbuLhTTn7AcNKHI',
    appId: '1:664222473723:web:d7f34f54cf094ee980bf5e',
    messagingSenderId: '664222473723',
    projectId: 'chat-app-b594b',
    authDomain: 'chat-app-b594b.firebaseapp.com',
    storageBucket: 'chat-app-b594b.firebasestorage.app',
    measurementId: 'G-2WXC58WJ6Y',
  );
}
